# Generated by Django 2.2.7 on 2019-11-18 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='author',
        ),
        migrations.AddField(
            model_name='help',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject2',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
