# Generated by Django 2.2.7 on 2019-11-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0002_auto_20191114_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject2s', to='masterit.Subject')),
            ],
        ),
    ]
