# Generated by Django 2.2.7 on 2019-11-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0003_subject2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject2',
            name='teacher',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
