# Generated by Django 2.2.7 on 2019-11-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0004_subject2_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subjectname', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=300)),
            ],
        ),
    ]
