# Generated by Django 2.2.7 on 2019-11-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0005_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='subjectname',
            new_name='subject_name',
        ),
    ]
