# Generated by Django 2.2.7 on 2019-11-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0006_auto_20191115_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Help',
        ),
    ]
