# Generated by Django 2.2.7 on 2019-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0007_auto_20191115_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject2',
            name='experience',
            field=models.TextField(default='College degree'),
        ),
        migrations.AddField(
            model_name='subject2',
            name='photo_url',
            field=models.TextField(default='image'),
        ),
        migrations.AlterField(
            model_name='help',
            name='body',
            field=models.TextField(),
        ),
    ]
