# Generated by Django 2.2.7 on 2019-11-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0008_auto_20191115_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject2',
            old_name='name',
            new_name='what_you_are_teaching',
        ),
        migrations.RenameField(
            model_name='subject2',
            old_name='teacher',
            new_name='your_name',
        ),
    ]
