# Generated by Django 2.2.7 on 2019-11-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0011_auto_20191116_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject2',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='subject2',
            name='photo',
            field=models.ImageField(default='blank', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subject2',
            name='your_name',
            field=models.CharField(default='your name', max_length=100),
        ),
    ]
