# Generated by Django 2.2.7 on 2019-11-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0012_auto_20191116_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject2',
            name='your_name',
        ),
        migrations.AddField(
            model_name='subject2',
            name='author',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
