# Generated by Django 2.2.7 on 2019-11-17 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0013_auto_20191117_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject2',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
