# Generated by Django 2.2.7 on 2019-11-18 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0016_auto_20191118_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
