# Generated by Django 2.2.7 on 2019-11-18 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0019_auto_20191118_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
