# Generated by Django 2.2.7 on 2019-11-18 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterit', '0021_auto_20191118_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='name',
        ),
        migrations.AddField(
            model_name='help',
            name='author',
            field=models.ForeignKey(default='name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
