# Generated by Django 2.2.7 on 2019-11-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterit', '0022_auto_20191118_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='author',
        ),
        migrations.AddField(
            model_name='help',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
